benutzer=
passwort=
http.proxyHost=
http.proxyPort=
https.proxyHost=
https.proxyPort=
katalog=

#1= Validieren, 2 = Validieren und Übertragen
action=
#upload, download test
aufgabe=upload
speichernunter_zip=
timeoutinms=3600000
