namespace XmlEditorUi;

public static class HeaderTemplateFields
{
    public static IReadOnlyList<TemplateFieldDefinition> EssentialFields { get; } =
    [
        new("Generator Info", "HEADER/GENERATOR_INFO"),
        new("Catalog Language", "HEADER/CATALOG/LANGUAGE"),
        new("Catalog ID", "HEADER/CATALOG/CATALOG_ID"),
        new("Catalog Version", "HEADER/CATALOG/CATALOG_VERSION"),
        new("Catalog Name", "HEADER/CATALOG/CATALOG_NAME"),
        new("Generation Date", "HEADER/CATALOG/GENERATION_DATE"),
        new("Creator First Name", "HEADER/DOCUMENT_CREATOR/FIRST_NAME"),
        new("Creator Last Name", "HEADER/DOCUMENT_CREATOR/LAST_NAME"),
        new("Creator Phone", "HEADER/DOCUMENT_CREATOR/PHONE"),
        new("Creator ID", "HEADER/DOCUMENT_CREATOR/ID_DB"),
        new("Creator Address Name", "HEADER/DOCUMENT_CREATOR/ADDRESS/NAME"),
        new("Creator Address Street", "HEADER/DOCUMENT_CREATOR/ADDRESS/STREET"),
        new("Creator Address ZIP", "HEADER/DOCUMENT_CREATOR/ADDRESS/ZIP"),
        new("Creator Address City", "HEADER/DOCUMENT_CREATOR/ADDRESS/CITY"),
        new("Creator Address Country", "HEADER/DOCUMENT_CREATOR/ADDRESS/COUNTRY"),
        new("Creator Address URL", "HEADER/DOCUMENT_CREATOR/ADDRESS/URL"),
        new("Creator Address ID", "HEADER/DOCUMENT_CREATOR/ADDRESS/ID_DB"),
        new("Creator Contact Remarks", "HEADER/DOCUMENT_CREATOR/CONTACT_REMARKS"),
        new("Recipient ID", "HEADER/RECIPIENT/RECIPIENT_ID"),
        new("Recipient Name", "HEADER/RECIPIENT/RECIPIENT_NAME"),
        new("Recipient Address Name", "HEADER/RECIPIENT/ADDRESS/NAME"),
        new("Recipient Address Street", "HEADER/RECIPIENT/ADDRESS/STREET"),
        new("Recipient Address ZIP", "HEADER/RECIPIENT/ADDRESS/ZIP"),
        new("Recipient Address City", "HEADER/RECIPIENT/ADDRESS/CITY"),
        new("Recipient Address Country", "HEADER/RECIPIENT/ADDRESS/COUNTRY"),
        new("Recipient Address URL", "HEADER/RECIPIENT/ADDRESS/URL"),
        new("Supplier ID", "HEADER/SUPPLIER/SUPPLIER_ID"),
        new("Supplier Name", "HEADER/SUPPLIER/SUPPLIER_NAME"),
        new("Supplier Address Name", "HEADER/SUPPLIER/ADDRESS/NAME"),
        new("Supplier Address Name2", "HEADER/SUPPLIER/ADDRESS/NAME2"),
        new("Supplier Address Street", "HEADER/SUPPLIER/ADDRESS/STREET"),
        new("Supplier Address ZIP", "HEADER/SUPPLIER/ADDRESS/ZIP"),
        new("Supplier Address City", "HEADER/SUPPLIER/ADDRESS/CITY"),
        new("Supplier Address State", "HEADER/SUPPLIER/ADDRESS/STATE"),
        new("Supplier Address Country", "HEADER/SUPPLIER/ADDRESS/COUNTRY"),
        new("Supplier Address Phone", "HEADER/SUPPLIER/ADDRESS/PHONE"),
        new("Supplier Address Mobile", "HEADER/SUPPLIER/ADDRESS/MOBILE"),
        new("Supplier Address Email", "HEADER/SUPPLIER/ADDRESS/EMAILS/EMAIL"),
        new("Supplier Address URL", "HEADER/SUPPLIER/ADDRESS/URL"),
        new("Supplier Contact Role", "HEADER/SUPPLIER/CONTACT/CONTACT_ROLE"),
        new("Supplier Contact Salutation", "HEADER/SUPPLIER/CONTACT/SALUTATION"),
        new("Supplier Contact First Name", "HEADER/SUPPLIER/CONTACT/FIRST_NAME"),
        new("Supplier Contact Last Name", "HEADER/SUPPLIER/CONTACT/LAST_NAME"),
        new("Supplier Contact Phone", "HEADER/SUPPLIER/CONTACT/PHONE"),
        new("Supplier Contact Mobile", "HEADER/SUPPLIER/CONTACT/MOBILE"),
        new("Supplier Contact Email", "HEADER/SUPPLIER/CONTACT/EMAILS/EMAIL"),
        new("Supplier Contact URL", "HEADER/SUPPLIER/CONTACT/URL"),
        new("Supplier Contact ID", "HEADER/SUPPLIER/CONTACT/ID_DB"),
        new("Supplier Contact Remarks", "HEADER/SUPPLIER/CONTACT/CONTACT_REMARKS"),
    ];
}
